import fs from 'node:fs/promises';
import path from 'node:path';
import {load} from 'cheerio';
const origin='https://bridal-esthe.tokyo';
const pages=[['home','/','HOME'],['about','/pages/about','ABOUT'],['about-service','/pages/about-service','SERVICE'],['frontpage','/collections/frontpage','COSME'],['contact','/pages/contact','CONTACT'],['faq','/pages/faq','FAQ'],['refund-policy','/policies/refund-policy','返金ポリシー'],['privacy-policy','/policies/privacy-policy','プライバシーポリシー']];
const images=new Map();
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function asset(src){const url=new URL(src,origin);url.search='';const file=decodeURIComponent(path.basename(url.pathname));images.set(url.href,`public/assets/images/${file}`);return `/assets/images/${encodeURIComponent(file)}`;}
function clean(html){const $=load(html,null,false);$('script,style,link,noscript,svg,form,iframe').remove();
  $('*').each((_,el)=>{const tag=el.tagName; const attrs={...el.attribs}; for(const key of Object.keys(attrs))$(el).removeAttr(key);
    if(tag==='img'){if(!attrs.src){$(el).remove();return;}$(el).attr({src:asset(attrs.src),alt:attrs.alt||'',loading:'lazy',...(attrs.width?{width:attrs.width,height:attrs.height||attrs.width}:{})});}
    if(tag==='a'){let href=attrs.href||'';if(href.startsWith(origin))href=href.slice(origin.length)||'/';if(href==='/collections/all')href='/collections/frontpage';if(href && /^(https?:\/\/|\/|#)/.test(href))$(el).attr('href',href);else $(el).replaceWith($(el).contents());}
    if(attrs.id==='reservation')$(el).attr('id','reservation');
  });
  $('span').each((_,el)=>$(el).replaceWith($(el).contents()));return $.html();}
const nav=pages.slice(0,6).map(([,url,label])=>`<a href="${url}">${label}</a>`).join('');
const cta='<aside class="booking"><p class="eyebrow">RESERVATION</p><h2>ご予約・ご相談はLINEから</h2><p>日程と出張先をお伺いいたします。ご自宅以外をご希望の場合もご相談ください。</p><a class="button" href="https://lin.ee/TQHW3Hf">LINEで予約・相談する <span aria-hidden="true">↗</span></a></aside>';
function document(title,route,body,description){return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}｜BRIDAL ESTHE LAUT</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${origin}${route}"><meta property="og:title" content="${escape(title)}｜BRIDAL ESTHE LAUT"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}${route}"><meta property="og:image" content="${origin}${asset('/cdn/shop/files/bridal-ogp.png')}"><link rel="stylesheet" href="/assets/style.css"><script src="/assets/site.js" defer></script></head><body><a class="skip" href="#main">本文へ移動</a><header><a class="brand" href="/">BRIDAL ESTHE <b>LAUT</b></a><button class="menu" aria-controls="navigation" aria-expanded="false">メニュー</button><nav id="navigation" aria-label="メインメニュー">${nav}</nav></header><main id="main">${body}${cta}</main><footer><a class="brand" href="/">BRIDAL ESTHE <b>LAUT</b></a><p>最高の日を最高の自分で。</p><nav aria-label="フッターメニュー">${nav}<a href="/policies/refund-policy">返金ポリシー</a><a href="/policies/privacy-policy">プライバシーポリシー</a><a href="https://g.co/kgs/nH2nts5">SALON ↗</a></nav><small>© ${new Date().getFullYear()} BRIDAL ESTHE LAUT. All rights reserved.</small></footer></body></html>`;}
async function write(route,html){const file=route==='/'?'public/index.html':`public${route}/index.html`;await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,html);}
const products=JSON.parse(await fs.readFile('migration/source/products.json','utf8')).products;
for(const [name,route,label] of pages){const $=load(await fs.readFile(`migration/source/${name}.html`,'utf8'));let body='';
  if(name==='frontpage'){body='<section class="page-heading"><p class="eyebrow">COSME</p><h1>毎日のケアに、美しさを。</h1><p>化粧品・美顔器のご紹介。商品のご購入についてはLINEからお問い合わせください。</p></section><div class="products">'+products.map(p=>`<article><a href="/products/${escape(p.handle)}">${p.images[0]?`<img src="${asset(p.images[0].src)}" alt="${escape(p.title)}" loading="lazy" width="500" height="500">`:''}<h2>${escape(p.title)}</h2><p>¥${Number(p.variants[0].price).toLocaleString('ja-JP')}</p><span>詳しく見る →</span></a></article>`).join('')+'</div>';}
  else if(name==='contact'){const image=$('main img').first().attr('src');body=`<section class="hero compact">${image?`<img src="${asset(image)}" alt="" width="1500" height="1000">`:''}<div><p class="eyebrow">CONTACT</p><h1>お問い合わせ</h1><p>サービスに関するお問い合わせや、出張サービスのご予約等、お気軽にお問い合わせください。</p></div></section><section class="prose"><h2>実店舗のご紹介</h2><p>完全予約制のため、まずはLINEからお問い合わせください。</p><h3>BEAUTY LAUT</h3><p>営業時間は不定期のため、お問い合わせください。</p><p><a href="https://bibixtutobeauty.com/2023/10/25/bauty-laut/">店舗のご紹介 ↗</a>　<a href="https://g.co/kgs/nH2nts5">Googleマップで確認 ↗</a></p></section>`;}
  else if(name.endsWith('policy')){body=`<section class="prose"><h1>${label}</h1>${clean($('.shopify-policy__body').html()||'')}</section>`;}
  else {$('main > section').each((i,el)=>{const section=$(el);const heading=section.find('h1,h2').first().text().trim();const singleColumn=(name==='about-service' && heading==='施術までの流れについて') || (name==='about' && heading==='施術内容・器具、施術の流れについて');const image=singleColumn?undefined:section.find('img').first().attr('src');
    if(i===0 && image){const text=section.find('.slideshow__text,.banner__text').first().html()||'';body+=`<section class="hero ${name==='home'?'':'compact'}"><img src="${asset(image)}" alt="" width="1500" height="1000" fetchpriority="high"><div><p class="eyebrow">${name==='home'?'BRIDAL ESTHE AT YOUR HOME':label}</p><h1>${escape(heading)}</h1>${clean(text)}${name==='home'?'<a class="button" href="/pages/about-service">サービスについて →</a>':''}</div></section>`;return;}
    if(section.find('details').length){body+='<section class="prose faq">'+section.find('details').toArray().map(el=>clean($.html(el))).join('')+'</section>';return;}
    const rte=section.find('.rte').toArray().filter(el=>!$(el).parents('.rte').length).map(el=>clean($(el).html()||'')).join('');
    if(!heading&&!rte)return;if(heading.includes('ご予約はLINE'))return;
    body+=`<section class="${image?'feature':'prose'}">${image?`<img src="${asset(image)}" alt="${escape(heading)}" loading="lazy" width="750" height="750">`:''}<div>${heading?`<h2>${escape(heading)}</h2>`:''}${rte}${image?'<a class="text-link" href="/pages/about">施術内容について →</a>':''}</div></section>`;
  });}
  if(!body.includes('<h1>'))body=body.replace(/<h2>([\s\S]*?)<\/h2>/,'<h1>$1</h1>');
  const description=$('meta[name="description"]').attr('content')||'美肌と小顔に特化したブライダルエステ出張サービス。';await write(route,document(name==='home'?'最高の日を最高の自分で。':label,route,body,description));
}
for(const p of products){const route='/products/'+p.handle;await write(route,document(p.title,route,`<section class="product-detail"><div>${p.images.map(im=>`<img src="${asset(im.src)}" alt="${escape(p.title)}" loading="lazy" width="600" height="600">`).join('')}</div><div><p class="eyebrow">COSME</p><h1>${escape(p.title)}</h1><p class="price">¥${Number(p.variants[0].price).toLocaleString('ja-JP')}</p><p>ご購入・在庫の確認はLINEからお問い合わせください。</p><a class="button" href="https://lin.ee/TQHW3Hf">商品について問い合わせる ↗</a><div class="product-copy">${clean(p.body_html)}</div></div></section>` ,p.title));}
await fs.mkdir('migration',{recursive:true});await fs.writeFile('migration/images.json',JSON.stringify([...images].map(([url,file])=>({url,file})),null,2));
await fs.writeFile('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...pages.map(p=>p[1]),...products.map(p=>'/products/'+p.handle)].map(route=>`<url><loc>${escape(origin+route)}</loc></url>`).join('')}</urlset>`);
console.log(`変換完了: ${pages.length+products.length}ページ、${images.size}画像`);
